### ISSUE TITLE
Provider Behaviors

### ISSUE THREAD

**Issue by guilsch** [sonia-auv/provider_kill_mission#33]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Context
The kill switch msg and mission switch msg don't havethe same behaviors when they are used. The mission switch is much longer to get when the state changes.

## Changes
Standardize the behavior of the provider to reduce the code and simply it. For example, have the mission switch msg always publish his state like the kill switch msg or the opposite, send a msg only when changing state.

## Comments
I have included a bag showing the behavior of the provider kill mission on teams and a testing bag with the interface_rs485 msg to test the feature.

**Comment by Kam0ss** [comment]
See latch option in publishers : http://wiki.ros.org/roscpp/Overview/Publishers%20and%20Subscribers
